#!/bin/bash
# Start public-facing HTTP servers.
set -Eeuo pipefail

if [[ -d "/etc/nginx" ]]; then
  sudo systemctl start nginx || true
fi

if [[ -d "/etc/apache2" ]]; then
  sudo systemctl start apache2 || true
fi

if [[ -f "/etc/turnserver.conf" ]]; then
  sudo systemctl start coturn || true
fi
