#!/bin/bash
# Stop public-facing HTTP servers.
set -Eeuo pipefail

if [[ -d "/etc/nginx" ]]; then
  sudo systemctl stop nginx || true
fi

if [[ -d "/etc/apache2" ]]; then
  sudo systemctl stop apache2 || true
fi

if [[ -f "/etc/turnserver.conf" ]]; then
  sudo systemctl stop coturn || true
fi
