#!/bin/bash
# Attempt to renew any previously-obtained Let's Encrypt certificates that
# expire in less than 30 days. (Certificates last for 90 days.)
set -Eeuo pipefail

sudo certbot renew --agree-tos --quiet --pre-hook "/home/feross/config/server-stop" --post-hook "/home/feross/config/server-start"
